
service: faceRecognitionApp

provider:
  name: aws
  runtime: python3.8
  region: sa-east-1


functions:
  lambda_handler:
    handler: lambda_handler
    role: arn:aws:iam::056738692191:role/teste_faceapp
    events:
      - s3:
          bucket: clientuploadpictures
          event: s3:ObjectCreated:*
      