
service: FaceApp

provider:
  name: aws
  runtime: python3.7
  region: sa-east-1

functions:
  lambda_handler:
    name: lambda_handler
    handler: handler.lambda_handler
    role: arn:aws:iam::056738692191:role/teste_faceapp
    events:
      - s3:
          bucket: clienteupload
          event: s3:ObjectCreated:*

      - s3:
          bucket: clienterecognized
          event: s3:ObjectCreated:*
          rules:
            - prefix: images_recognition/
